collector_port: 3030

postgres_host: 192.0.2.10
postgres_port: 5432
postgres_user: postgres
postgres_password: password
postgres_dbname: kohaku
postgres_sslmode: disable

http2_h2c: true
http2_max_concurrent_streams: 250
http2_idle_timeout: 60