name: Go Build & Test

on:
  push:
    branches-ignore:
      - 'master'
    tags-ignore:
      - '*'

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.5

    - run: go version

    - run: go fmt .

    - name: Test
      run: GIN_MODE=release make test

    - name: Build
      run: make
